- composer.lock
Updatunty ssh tunnel keboola/ssh-tunnel#2
souvisí s keboola/syrup-router#50
> fix - ssh tunnel update - keep alive

- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLTest.php
ref: https://github.com/keboola/db-extractor-mysql/issues/22
> Validate table schema with connection database

- composer.lock
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
update to https://github.com/keboola/db-extractor-common/releases/tag/5.3.0
> Common update

- composer.json
- composer.lock
- src/run.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
- tests/data/mysql/config.json
Changes include:
- Update to common 6.1.0 (new retry method
- test retries
- support json configurations
> Json configuration support

- .gitignore
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
Changes: allow any timestamp column to be used for incremental fetching.
> incremental fetching patch

- src/run.php
> No longer output errors in KBC log

- README.md
- bootstrap.php
- composer.json
- composer.lock
- docker-compose.yml
- phpcs.xml
- phpunit.xml.dist
- src/Keboola/DbExtractor/Configuration/MySQLConfigDefinition.php
- src/Keboola/DbExtractor/Configuration/MySQLConfigRowDefinition.php
- src/Keboola/DbExtractor/Extractor/MySQL.php
- src/Keboola/DbExtractor/MySQLApplication.php
- src/run.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
- tests/Keboola/DbExtractor/MySQLSSLDifferentCnTest.php
- tests/Keboola/DbExtractor/MySQLSSLTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
> Updating to db-extractor-common 9

- src/Keboola/DbExtractor/Configuration/MySQLConfigDefinition.php
- src/Keboola/DbExtractor/Configuration/MySQLConfigRowDefinition.php
- tests/data/mysql/config.json
- tests/data/mysql/config.yml
> Piv allow advanced mode

- composer.json
- composer.lock
Updates the component to the latest common library version (9.1.1)
> Update to ex-db-common

- composer.json
- composer.lock
> Update to common 9.1.2

- composer.json
- composer.lock
- src/run.php
> update to common 9.1.4

- composer.lock
> Update to db-extractor-common 9.1.6

- composer.lock
fixes #66 and the deadConnection exception
> Update to common 9.1.7

- composer.lock
> Update to common 9.1.8

- src/Keboola/DbExtractor/Extractor/MySQL.php
Fixes #71 
Changes:
- this will propagate autoIncrement value from table to column only if table has it
> Set autoIncrement to column only if table has it

- composer.lock
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
> Improve metadata query performance

- docker-compose.yml
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
> Allow incremental fetching on datetime columns

- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLTest.php
> Update for mysql8 new defaults behaviour

- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLTest.php
> Fix error on db-schema mismatch

- src/Keboola/DbExtractor/Configuration/MySQLConfigDefinition.php
- src/Keboola/DbExtractor/Configuration/MySQLConfigRowDefinition.php
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLSSLDifferentCnTest.php
> Add option to allow invalid hosts for ssl certs

- composer.lock
- src/run.php
Update db-extractor-common
Catch ConfigUserException - Solves https://github.com/keboola/db-extractor-common/issues/131
> Catch config exception and update common

- composer.lock
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
Solving https://github.com/keboola/db-extractor-common/issues/128
> Check connecting via ssh tunnel

- composer.json
- composer.lock
- src/run.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
Solving https://github.com/keboola/db-extractor-common/issues/134
> Remove yaml config

- composer.json
- src/Keboola/DbExtractor/Extractor/MySQL.php
solving - https://keboola.atlassian.net/browse/COM-35
> Retryable queries

- tests/env/sshproxy/Dockerfile
Solving - https://keboola.atlassian.net/browse/COM-54
> Update ubuntu version in sshproxy

- composer.json
- composer.lock
- src/Keboola/DbExtractor/Extractor/MySQL.php
Missing method for get max incremental value
> Method for max increment max value

- composer.json
- composer.lock
- src/Keboola/DbExtractor/MySQLApplication.php
Part of - https://keboola.atlassian.net/browse/COM-49
> Recognition config row

- composer.json
- composer.lock
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
Solving - https://keboola.atlassian.net/browse/COM-25
> Get tables format

- composer.json
- composer.lock
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLTest.php
fixes - https://keboola.slack.com/archives/C035LGNK5/p1578309422000400
> fix gettables with no column

- src/Keboola/DbExtractor/Extractor/MySQLMetadataProvider.php
- tests/Keboola/DbExtractor/AbstractMySQLTest.php
- tests/Keboola/DbExtractor/MySQLEntrypointTest.php
- tests/Keboola/DbExtractor/MySQLTest.php
- tests/Keboola/DbExtractor/QueryGenerationTest.php
Changes:
- Fix bug, when one column has multiple FKs (in MySQL it is possible).
> Fix getTables bug, `foreign key is already set`

- composer.json
- composer.lock
- src/Keboola/DbExtractor/Extractor/MySQL.php
Solving - https://keboola.atlassian.net/browse/COM-265
> update db-ex-* packages

- src/Keboola/DbExtractor/Extractor/MySQLMetadataProvider.php
Solving: https://keboola.atlassian.net/browse/COM-387
Slack: https://keboola.slack.com/archives/C09U3R1J4/p1597383286014500
> Fix rare metadata loading error

- README.md
- src/Keboola/DbExtractor/Configuration/NodeDefinition/MysqlDbNode.php
- src/Keboola/DbExtractor/Configuration/ValueObject/MysqlDatabaseConfig.php
- src/Keboola/DbExtractor/Extractor/MySQL.php
- tests/Keboola/DbExtractor/MySQLTest.php
Solving - https://keboola.atlassian.net/browse/COM-378
> transaction isolation level

- Dockerfile
- composer.json
- composer.lock
- phpstan.neon
- src/Keboola/DbExtractor/Extractor/MySQL.php
- src/Keboola/DbExtractor/Extractor/MySQLDbConnection.php
- src/Keboola/DbExtractor/Extractor/MySQLMetadataProvider.php
- tests/functional/error-incremental-fetching-fake-column/expected-stdout
- tests/functional/error-incremental-fetching-string-column/expected-stdout
- tests/functional/error-run-action-without-database/expected-stdout
- tests/functional/incremental-fetching-empty-rows/expected-stderr
- tests/functional/incremental-fetching-empty-rows/expected-stdout
- tests/functional/run-action-emoji/expected-stdout
- tests/functional/run-action-row/expected-stdout
- tests/functional/ssl-test-cipher/expected-stdout
- tests/functional/test-retries/expected-stdout
- tests/phpunit/MySQLTest.php
Jira - https://keboola.atlassian.net/browse/COM-604
> Update common v14

- .github/workflows/push.yml
Jira - https://keboola.atlassian.net/browse/COM-936
> Add docker login

- composer.json
- composer.lock
- tests/functional/ssl-test-connection/source/data/config.json
Jira: https://keboola.atlassian.net/browse/COM-1044
> Make config key 'ssl.key' secret

- deploy.sh
Slack: https://keboola.slack.com/archives/CQ1ASK06M/p1629390541104500
Changes:
- Fixed `deploy.sh`, deploy only semantic tags.
> Fix deploy.sh

- .github/workflows/push.yml
Changes:
- Simplified GH action.
> Simplify GH workflow

- composer.json
- composer.lock
https://github.com/keboola/db-extractor-config/pull/28
> SSLConnectionConfig: convert empty strings to null

- src/Keboola/DbExtractor/Extractor/MySQLMetadataProvider.php
https://keboola.atlassian.net/browse/COM-390
Dohodnuto bez testu viz https://keboola.slack.com/archives/CQ1ASK06M/p1647879742928589?thread_ts=1647879256.223889&cid=CQ1ASK06M
> Handle load metadata errors as user exception

- src/Keboola/DbExtractor/Extractor/MySQLDbConnection.php
Jira - https://keboola.atlassian.net/browse/COM-1545
> Extend retry interval

- composer.json
- composer.lock
- phpstan.neon
- src/Keboola/DbExtractor/MySQLApplication.php
- src/run.php
- tests/functional/incremental-fetching-empty-rows/expected-stdout
- tests/functional/network-compression/expected-stdout
- tests/functional/run-action-emoji/expected-stdout
- tests/functional/run-action-row/expected-stdout
- tests/functional/run-no-rows/expected-stdout
- tests/functional/run-query-no-rows/expected-stdout
- tests/functional/ssl-different-cn/expected-stderr
- tests/functional/test-ssh-tunnel-connectien-retries/expected-stderr
- tests/phpunit/ConfigTest.php
- tests/phpunit/MySQLTest.php
- tests/phpunit/PerformanceTest.php
Jira - https://keboola.atlassian.net/browse/COM-1637
> Update common packages

- .github/workflows/push.yml
- README.md
- composer.lock
- tests/phpunit/MySQLTest.php
JIRA: 
- https://keboola.atlassian.net/browse/PST-1996
- https://keboola.atlassian.net/browse/PST-2025
SLACK: https://keboolaglobal.slack.com/archives/C055HSMKX51/p1723642181597589?thread_ts=1723214328.361609&cid=C055HSMKX51
> Update db-extractor-common to latest version which fails when trying to set PK on non-existing column (case insensitive)

- composer.json
- composer.lock
[PST-2098](https://keboola.atlassian.net/browse/PST-2098)
[PST-2098]: https://keboola.atlassian.net/browse/PST-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PST-2098: ssh-tunnel with ConnectTimeout

- src/Keboola/DbExtractor/Configuration/NodeDefinition/MysqlDbNode.php
- src/Keboola/DbExtractor/Configuration/ValueObject/MysqlDatabaseConfig.php
- src/Keboola/DbExtractor/Extractor/MySQLDbConnectionFactory.php
https://keboola.atlassian.net/browse/SUPPORT-7908
> config option: add query timeout

- composer.json
- composer.lock
https://keboola.atlassian.net/browse/PST-2322
> PST-2322: Update db-extractor-common to ^17.2

- .github/workflows/push.yml
- docker-compose.yml
- docker/mysql-entrypoint.sh
- docker/mysql-ssl/9.1/conf.d/ssl.cnf
https://keboola.atlassian.net/browse/PST-2286
> Update PST-2286: CI Test for mysql ver 9.1
